version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - mynetwork
    environment:
      MONGO_URI: mongodb+srv://sajangautam7090:So2EWZHtRBOjkivF@onlineide.363wtkb.mongodb.net/?retryWrites=true&w=majority&appName=onlineIDE

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
